#!/bin/bash

SCRIPTDIR=$(dirname $(readlink -f $0))
ROOTDIR=$(cd ${SCRIPTDIR}/.. && git rev-parse --show-toplevel)

TARGET=${ROOTDIR}
mkdir -p ${TARGET}

CMAKEFLAGS=
if [ "$1" == "debug" ]; then
    CMAKEFLAGS='-DCMAKE_BUILD_TYPE=Debug'
    mkdir -p debug
    cd debug
else
    CMAKEFLAGS='-DCMAKE_BUILD_TYPE=Release'
    mkdir -p release
    cd release
fi

cmake \
    ${CMAKEFLAGS} \
    -DCMAKE_INSTALL_PREFIX:PATH=${TARGET} \
    -DCMAKE_INSTALL_INCLUDEDIR:PATH=${TARGET}/include/bddc \
    -DCMAKE_INSTALL_LIBDIR:PATH=${TARGET}/lib64 \
    ..

make install

