#!/bin/bash

CMAKEFLAGS=
if [ "$1" == "debug" ]; then
    CMAKEFLAGS='-DCMAKE_BUILD_TYPE=Debug'
fi

SCRIPTDIR=$(dirname $(readlink -f $0))
ROOTDIR=$(cd ${SCRIPTDIR}/.. && git rev-parse --show-toplevel)

TARGET=${ROOTDIR}/usr
mkdir -p ${TARGET}
mkdir -p build
cd build

cmake \
    ${CMAKEFLAGS} \
    -DCMAKE_INSTALL_PREFIX:PATH=${TARGET} \
    -DCMAKE_INSTALL_INCLUDEDIR:PATH=${TARGET}/include/bddc \
    -DCMAKE_INSTALL_LIBDIR:PATH=${TARGET}/lib64 \
    ..

make install

